version: "3.9"

services:
  mail:
    build: .
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
    restart: always

networks:
  default:
    external: true
    name: mup-network
